GET http://localhost:3000/art

### 

POST http://localhost:3000/register
Content-Type: application/json

{
  "email": "Mikel@bond.com",
  "password": "123456"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "Mikel@bond.com",
  "password": "123456"
}